version: '3.1'
services:
  web:
    image: gardenermultitool
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
  api:
    image: gardenermultitool-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo