version: '3.1'
services:
  web:
    container_name: web
    image: gardenersmultitool
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
  api:
    container_name: api
    image: gardenersmultitool-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://*:5000;
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=gardeners-multitool
    ports:
      - 27018:27017
    volumes:
      - ~/docker/volumes/mongodb:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ../plant.json:/docker-entrypoint-initdb.d/plant.json:ro